print("Enter your name:")
x = input()
print("Hello, " + x)
print("do you need help with your homework,lets try addition,enter a number:")
y = input()
print("enter another number:")
z = input()
a = int(y)+int(z)
print(a)
